### PR TITLE
Migration to internal Graphite

### PR DESCRIPTION
**Pull request by bjfletcher**

### CODE REVIEW

**Comment by bjfletcher** [comment]
Outstanding issues

Note: see what they're meant to look like here: http://next-radiator.ft.com/

1. 5xx error codes per application
(on internal, it doesn't show the "stacked" graph with different colours... it shows just one colour for all bars)

https://graphite-api.ft.com/render/?bgcolor=FFFFFF&fgcolor=000000&target=groupByNode(maximumAbove(next.heroku.*.*.express.default_route_GET.res.status.5*.count,5),1,%27sumSeries%27)&areaMode=stacked&width=832.5&height=220&hideLegend=false&lineMode=connected&from=-4h&yDivisors=1&minorY=1

2. Router proxy hangups (ECONNRESET)

https://graphite-api.ft.com/render/?bgcolor=FFFFFF&fgcolor=000000&target=color(drawAsInfinite(next.heroku.{*}.*.express.start),%27cccccc%27)&target=color(sumSeries(movingAverage(next.heroku.router.*.proxy-server.events.hangUp.count,10)),%20%27red%27)&target=color(movingAverage(timeShift(averageSeries(next.heroku.router.*.proxy-server.events.hangUp.count),%277d%27),%2010),%27999999%27)&width=832.5&height=150&lineMode=connected&from=-4h&yDivisors=1&minorY=1

3. Router response time

https://graphite-api.ft.com/render/?bgcolor=FFFFFF&fgcolor=000000&target=color(drawAsInfinite(next.heroku.{*}.*.express.start),%27cccccc%27)&target=color(movingAverage(averageSeries(next.heroku.router.*.http.res.status_2xx_response_time.mean),10),%2737DF24%27)&target=color(movingAverage(timeShift(averageSeries(next.heroku.router.*.http.res.status_2xx_response_time.mean),%277d%27),%2010),%27999999%27)&width=832.5&height=150&hideLegend=true&lineMode=connected&from=-4h&yDivisors=1&minorY=1

4. Router 5xx errors and timeouts

https://graphite-api.ft.com/render/?bgcolor=FFFFFF&fgcolor=000000&target=sumSeries(next.heroku.router.*.http.res.status_5xx.count)&target=sumSeries(next.heroku.router.*.server.events.socket.timeout.count)&width=832.5&height=150&hideLegend=false&lineMode=connected&from=-4h&yDivisors=1&minorY=1

5. Application restarts

https://www.hostedgraphite.com/bbaf3ccf/3764fd14-6bd9-42e5-903f-03aae5ef2a07/graphite/render/?_salt=1416939293.909&bgcolor=FFFFFF&fgcolor=000000&target=legendValue(aliasByNode(drawAsInfinite(sortByTotal(groupByNode(currentAbove(heroku.*.*.express.start,0),1,%22sumSeries%22))),0),%22total%22)&width=832.5&height=200&hideLegend=false&lineMode=connected&from=-1h&yDivisors=1&minorY=1

**Comment by captain-sysadmin** [comment]
1) was an interesting one. this should be correct: https://graphite-api.ft.com/render/?bgcolor=FFFFFF&fgcolor=000000&target=groupByNode(maximumAbove(next.heroku.*.*.express.default_route_GET.res.status.5*.count,5),2,%27sumSeries%27)&areaMode=stacked&width=832.5&height=220&hideLegend=false&lineMode=connected&from=-4h&yDivisors=1&minorY=1

The function "groupByNode" needed its index moved up on (because its not heroku.* its next.heroku.*)

**Comment by captain-sysadmin** [comment]
2) I don't think the data exists any more. Did we get rid of the router and use fastly instead?

**Comment by captain-sysadmin** [comment]
Hmm actually, I don't think the router data exists in internal graphite....

**Comment by captain-sysadmin** [comment]
4) I can't seem to find the data again.

5) seems to work ok,

**Comment by bjfletcher** [comment]
5. my mistake - it's still using hosted graphite, will fix

**Comment by bjfletcher** [comment]
To update... all have been fixed, mainly thanks to the router now pumping into internal Graphite.

Just this issue still outstanding:

https://graphite-api.ft.com/render/?bgcolor=FFFFFF&fgcolor=000000&target=legendValue(aliasByNode(drawAsInfinite(sortByTotal(groupByNode(currentAbove(next.heroku.*.*.express.start,0),1,%22sumSeries%22))),0),%22total%22)&width=792.9&height=200&hideLegend=false&lineMode=connected&from=-1h&yDivisors=1&minorY=1

which doesn't work.

**Pull request merged**
